apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{service}}
        version: v1
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      imagePullSecrets:
        - name: ecr-secret
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{namespace}}
  name: {{service}}
spec:
  selector:
    k8s-app: {{service}}
  ports:
  - port: 8080
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  rules:
  - host: eureka.{{team}}.twu-china.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
