kind: Deployment
apiVersion: apps/v1
metadata:
  name: eureka-server
  namespace: team-a-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: eureka-server
  template:
    metadata:
      namespace: team-a-dev
      labels:
        k8s-app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: 076880417388.dkr.ecr.cn-northwest-1.amazonaws.com.cn/team-a:eureka-server-8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-secret
---
kind: Service
apiVersion: v1
metadata:
  namespace: team-a-dev
  name: eureka-server
spec:
  selector:
    k8s-app: eureka-server
  ports:
  - port: 8080
    name: http
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka-server
  namespace: team-a-dev
spec:
  rules:
  - host: eureka.team-a.twu-china.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: eureka-server
          servicePort: 8080